name: 'Pixee'

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

jobs:
  pixee_fix:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:      
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Python script to create PR
        uses: docker://pixeematt/ci-test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
